first if-statement in steamauth/userInfo.php
SmItH197/SteamAuthentication pull request #192
Opened 2017-11-14 21:14 UTC by AlaaAo

first if-statement in steamauth/userInfo.php should be edited to check $_SESSION['steamid']

2017-11-15 07:12 UTC, BlackCetha commented
I think you might've selected the wrong base commit/branch. You need to fork the master branch and edit only the file you want to change.

2017-12-18 14:40 UTC, Monkeynutz2010 approved these changes

2017-12-18 15:39 UTC, BlackCetha requested changes
Please select the current HEAD as base commit.

2018-09-20 06:18 UTC, BlackCetha commented
@SmItH197 Could you close this PR? It's been inactive and has the wrong base.

2019-04-08 17:28 UTC, closed without merging